# This file is a template, and might need editing before it works on your project.
# Official docker image.

variables:
  GIT_SUBMODULE_STRATEGY: "normal"
  IS_FXSERVER: "1"

stages:
  - prep
  - build
  - test
  - deploy

prep-linux:
  variables:
    BOOST_ROOT: "$CI_PROJECT_DIR\\libs\\boost_1_64_0"
  artifacts:
    paths:
    - fivem/code/bin
    untracked: true
  image: alpine:latest
  stage: prep
  variables:
      GIT_STRATEGY: clone
  script:
    docker ps
  tags:
  - docker
build:
  stage: prep
  tags:
    - win32
  cache:
    paths:
      - save\*
  before_script:
    - cmd /c "git clone `"https://github.com/citizenfx/fivem.git`" work"
    - ."$env:CI_PROJECT_DIR\Build-Scripts\scripts\fxs-components\componentLinker.ps1" -WorkDir "$env:CI_PROJECT_DIR\work" -SrcDir "$env:CI_PROJECT_DIR\."
    - cd work
  script:
    - ."$env:CI_PROJECT_DIR\Build-Scripts\scripts\fxs-components\FiveM.ps1" -WorkDir "$env:CI_PROJECT_DIR\work" -SaveDir "$env:CI_PROJECT_DIR\save"

  artifacts:
    paths:
    - save\bin
    - work\out
  deploy:
    tags:
      - win32
    when: manual
    stage: deploy
    script:
      - stop-service fxserver-gitlab
      - 7z x -y -o $env:DEPLOY_PATH $env:CI_PROJECT_DIR\work\out\server.zip
      - start-service fxserver-gitlab