# This file is a template, and might need editing before it works on your project.
# Official docker image.

variables:
  BOOST_ROOT: "$CI_PROJECT_DIR\\libs\\boost_1_64_0"
  GIT_SUBMODULE_STRATEGY: "normal"
  IS_FXSERVER: "1"

stages:
  - prep
  - build
  - test
  - deploy

prep-linux:
  artifacts:
    paths:
    - fivem/code/bin
    untracked: true
  image: alpine:latest
  stage: prep
  variables:
      GIT_STRATEGY: clone
  script:
    docker ps
  tags:
  - docker
build:
  stage: prep
  tags:
    - win32
  cache:
    paths:
      - libs\boost_1_64_0
      - save\*
  before_script:

    #- powershell -File $CI_PROJECT_DIR\Build-Scripts\scripts\fxs-components\Installer.ps1 -mode premake
    - .$env:CI_PROJECT_DIR\Build-Scripts\scripts\fxs-components\Installer.ps1 -mode boost
    - cmd /c "git clone `"https://github.com/citizenfx/fivem.git`" work"
    - cd fivem
    - New-Item -ItemType Junction -Path $env:CI_PROJECT_DIR\fivem\code\components -Name fs-web -Value $env:CI_PROJECT_DIR\components\fs-web
    - Add-Content -Value "component 'fs-web'" -Path $env:CI_PROJECT_DIR\fivem\code\components\config.lua -Encoding UTF8
    #- git submodule update --init --recursive
  script:
    - ."$env:CI_PROJECT_DIR\Build-Scripts\scripts\fxs-components\FiveM.ps1" -WorkDir "$env:CI_PROJECT_DIR\wprk" -SaveDir "$env:CI_PROJECT_DIR\save"

  artifacts:
    paths:
    - save\bin
    - work\out