# This file is a template, and might need editing before it works on your project.
# Official docker image.

variables:
  BOOST_ROOT: "%CI_PROJECT_DIR%\\libs\\boost_1_64_0"
  GIT_SUBMODULE_STRATEGY: "normal"
  GIT_STRATEGY: clone

stages:
  - prep
  - build
  - test
  - deploy

prep-linux:
  artifacts:
    paths:
    - fivem/code/bin
    untracked: true
  image: alpine:latest
  stage: prep
  before_script:
    - apk --no-cache update
    - apk --no-cache upgrade
    - apk add git
    - git clone https://github.com/citizenfx/fivem.git
    
  script:
    - cd fivem
    - git submodule update --init --recursive
    - ln -sf $CI_PROJECT_DIR/components/fs-web $CI_PROJECT_DIR/fivem/code/components/fs-web
    - echo "component 'fs-web'" >> $CI_PROJECT_DIR/fivem/code/components/config.lua
    - chmod +x $CI_PROJECT_DIR/Build-Scripts/scripts/fxs-components/fivem-linux.sh
    - $CI_PROJECT_DIR/Build-Scripts/scripts/fxs-components/fivem-linux.sh
  tags:
  - docker
prep:
  stage: prep
  tags:
  - win32
  before_script:
    - powershell -Command "Install-WindowsFeature NET-Framework-45-Core"
#    - powershell -Command "Invoke-WebRequest "https://aka.ms/vs/15/release/vs_BuildTools.exe" -OutFile vs_BuildTools.exe -UseBasicParsing ;
#      Start-Process -FilePath '.\vs_BuildTools.exe' -ArgumentList '--quiet', '--norestart', '--locale en-US', '--add Microsoft.Component.MSBuild`;Microsoft.VisualStudio.Component.CoreBuildTools`;Microsoft.VisualStudio.Component.Roslyn.Compiler`;Microsoft.VisualStudio.Workload.MSBuildTools`;Microsoft.VisualStudio.Component.VC.CoreBuildTools`;Microsoft.VisualStudio.Component.Windows10SDK' -Wait ;
#      Remove-Item .\vs_BuildTools.exe ;
#      Remove-Item -Force -Recurse 'C:\Program Files (x86)\Microsoft Visual Studio\Installer'"
    - powershell -NoProfile -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))"
    - SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"
  script:
    - choco install -y 7zip python2 vswhere git

build:
  stage: prep
  tags:
    - win32
  cache:
    paths:
      - libs\boost_1_64_0
    untracked: true
  before_script:
    - git clone https://github.com/citizenfx/fivem.git
    - git clone https://lab.idevelopment.be/FiveM-Scripts/Build-Scripts
    #- powershell -File %CI_PROJECT_DIR%\Build-Scripts\scripts\fxs-components\Installer.ps1 -mode premake
    - powershell -File %CI_PROJECT_DIR%\Build-Scripts\scripts\fxs-components\Installer.ps1 -mode boost
    - cd fivem
    - git submodule update --init --recursive
  script:
    - powershell -File "%CI_PROJECT_DIR%\Build-Scripts\scripts\fxs-components\FiveM.ps1"
   
