# This file is a template, and might need editing before it works on your project.
# Official docker image.

variables:
  BOOST_ROOT: "$CI_PROJECT_DIR\\libs\\boost_1_64_0"
  GIT_SUBMODULE_STRATEGY: "normal"
  GIT_STRATEGY: clone
  IS_FXSERVER: "1"

stages:
  - prep
  - build
  - test
  - deploy

prep-linux:
  artifacts:
    paths:
    - fivem/code/bin
    untracked: true
  image: alpine:latest
  stage: prep
  before_script:
    - apk --no-cache update
    - apk --no-cache upgrade
    - apk add git
    - git clone https://github.com/citizenfx/fivem.git
    
  script:
    - cd fivem
    - git submodule update --init --recursive
    - ln -sf $CI_PROJECT_DIR/components/fs-web $CI_PROJECT_DIR/fivem/code/components/fs-web
    - echo "component 'fs-web'" >> $CI_PROJECT_DIR/fivem/code/components/config.lua
    - chmod +x $CI_PROJECT_DIR/Build-Scripts/scripts/fxs-components/fivem-linux.sh
    - $CI_PROJECT_DIR/Build-Scripts/scripts/fxs-components/fivem-linux.sh
  tags:
  - docker
build:
  stage: prep
  tags:
    - win32
  cache:
    paths:
      - libs\boost_1_64_0
  before_script:
    - git clone https://github.com/citizenfx/fivem.git
    #- powershell -File $CI_PROJECT_DIR\Build-Scripts\scripts\fxs-components\Installer.ps1 -mode premake
    - $env:CI_PROJECT_DIR\Build-Scripts\scripts\fxs-components\Installer.ps1 -mode boost
    - cd fivem
    #- git submodule update --init --recursive
  script:
    - powershell -File "$env:CI_PROJECT_DIR\Build-Scripts\scripts\fxs-components\FiveM.ps1" -WorkDir "$env:CI_PROJECT_DIR\fivem" -SaveDir "$env:CI_PROJECT_DIR\save"
  artifacts:
    paths:
    - save\